@startuml Cineplanet
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false
skinparam usecase {
  BackgroundColor White
  BorderColor Black
}

'------------------- ACTORES -------------------
actor "Cliente" as Cliente
actor "Empleado" as Empleado
actor "Administrador" as Admin
actor "Sistema de Pago\n(externo)" as Pago

'------------------- AUTENTICACION -------------------
together {
  rectangle "Autenticación / Perfil" {
    (Registrarse) as RegistrarCliente
    (Login / Logout) as Login
    (Gestionar Perfil Cliente) as PerfilCliente
  }

  Cliente --> RegistrarCliente
  Cliente --> Login
  Cliente --> PerfilCliente
}

Cliente -[hidden]down- Empleado

'------------------- BOLETOS -------------------
together {
  rectangle "Gestión de Boletos" {
    (Comprar Boletos) as ComprarBoletosWeb
     
    (Seleccionar Función) as SeleccionarFuncion
    (Seleccionar Asientos) as SeleccionarAsientos
    (Emitir Boleta / Ticket) as EmitirBoleta
    (Cancelar Reserva) as CancelarReserva
    (Reembolso) as Reembolso

    ComprarBoletosWeb .> SeleccionarFuncion : <<include>>
    ComprarBoletosWeb .> SeleccionarAsientos : <<include>>
    ComprarBoletosWeb .> EmitirBoleta : <<include>>

    CancelarReserva .> Reembolso : <<extend>>
  }

  Cliente --> ComprarBoletosWeb
  Cliente --> CancelarReserva
  Empleado --> EmitirBoleta
  Empleado --> Reembolso
}

Empleado -[hidden]down- Admin

'------------------- DULCERIA -------------------
together {
  rectangle "Dulcería" {
    (Comprar Dulcería) as ComprarDulceriaSolo
    (Vender Dulcería) as VenderDulceria
    (Emitir Boleta Dulcería) as BoletaDulceria
    (Aplicar Combo) as AplicarCombo

    VenderDulceria .> BoletaDulceria : <<include>>
    ComprarDulceriaSolo .> BoletaDulceria : <<include>>
    AplicarCombo .> ComprarDulceriaSolo : <<extend>>
    AplicarCombo .> VenderDulceria : <<extend>>
  }

  Cliente --> ComprarDulceriaSolo
  Empleado --> VenderDulceria
}


'------------------- ADMINISTRACION -------------------
together {
  rectangle "Administración" {
    (Gestionar Cartelera) as GestionarCartelera
    (Programar Función) as ProgramarFuncion
    (Cancelar Función) as CancelarFuncion
    (Gestionar Sedes) as GestionarSedes
    (Registrar Personal) as RegistrarPersonal
    (Gestionar Roles y Permisos) as GestionarRoles
    (Generar Reportes) as Reportes

    ProgramarFuncion .> GestionarCartelera : <<include>>
    RegistrarPersonal .> GestionarRoles : <<include>>
    CancelarFuncion .> GestionarCartelera : <<extend>>
  }

  Admin --> GestionarCartelera
  Admin --> GestionarSedes
  Admin --> RegistrarPersonal
  Admin --> Reportes
  Admin --> CancelarFuncion
}

'------------------- PAGOS Y NOTIS -------------------
together {
  rectangle "Pagos y Notificaciones" {
    (Realizar Pago) as RealizarPago
    (Gestionar Caja) as GestionarCaja
    (Notificar Cliente) as NotificarCliente

    ComprarBoletosWeb .> RealizarPago : <<include>>
    ComprarDulceriaSolo .> RealizarPago : <<include>>
    VenderDulceria .> RealizarPago : <<include>>
    EmitirBoleta .> NotificarCliente : <<include>>
    CancelarFuncion .> NotificarCliente : <<extend>>
    Reembolso .> NotificarCliente : <<extend>>
  }

  Empleado --> GestionarCaja
  RealizarPago --> Pago
}
@enduml